In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
df = pd.read_excel("/content/Dataset_for_Data_Analytics.xlsx")

In [14]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [15]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [19]:
# replacing null values with "Not Applied" as referral cant be inserted here.
df['CouponCode'].fillna('Not Applied', inplace = True)

/tmp/ipykernel_1040/1901923788.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CouponCode'].fillna('Not Applied', inplace = True)

In [20]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [21]:
df.sample(5)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
814,ORD200814,2024-12-11,C50732,Chair,4,147.51,979 Main St,Debit Card,Pending,TRK21082461,4,WINTER15,Instagram,590.04
1125,ORD201125,2023-10-16,C23555,Desk,4,408.36,156 Main St,Gift Card,Cancelled,TRK67210247,4,FREESHIP,Referral,1633.44
798,ORD200798,2025-05-19,C20861,Phone,5,488.35,968 Main St,Debit Card,Returned,TRK89372013,9,FREESHIP,Email,2441.75
243,ORD200243,2025-05-09,C54725,Chair,2,144.66,506 Main St,Online,Cancelled,TRK30601940,7,FREESHIP,Google,289.32
76,ORD200076,2024-03-31,C58638,Laptop,4,382.88,239 Main St,Cash,Cancelled,TRK38224871,6,WINTER15,Email,1531.52

In [22]:
# rounding to 1 cause i dont like decimals greater or equal to 2
df['UnitPrice'] = df['UnitPrice'].round(1)
df['TotalPrice'] = df['TotalPrice'].round(1)

In [33]:
df.sample(4)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
462,ORD200462,2025-03-31,C22991,Phone,1,252.7,731 Main St,Online,Cancelled,TRK32796086,1,Not Applied,Referral,252.7
208,ORD200208,2024-10-08,C87777,Desk,2,408.3,597 Main St,Online,Shipped,TRK29003608,3,FREESHIP,Facebook,816.6
1045,ORD201045,2024-09-20,C11893,Laptop,5,316.4,671 Main St,Gift Card,Returned,TRK72012758,7,Not Applied,Email,1582.0
38,ORD200038,2024-12-19,C15924,Laptop,1,245.9,549 Main St,Debit Card,Delivered,TRK14835975,3,SAVE10,Google,245.9

Anomaly check

In [28]:
# checking for anomalies
(df['Quantity'] > df['ItemsInCart']).sum()

np.int64(0)

In [34]:
# No anomaly here
dff = df[(df['UnitPrice']*df['Quantity'] != df['TotalPrice'])]

In [35]:
dff.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.6,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.1
1,ORD200001,2024-08-23,C75739,Phone,2,151.4,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.7
2,ORD200002,2024-02-27,C81728,Tablet,5,550.7,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.4
5,ORD200005,2023-10-23,C37249,Phone,2,245.9,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.7
7,ORD200007,2023-05-12,C41460,Monitor,5,149.6,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.8

In [37]:
df['ReferralSource'].value_counts()

ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64

In [45]:
# checking if theres a particular pattern
df['ReferralSource'].groupby(df['CouponCode']).value_counts()

CouponCode   ReferralSource
FREESHIP     Instagram         73
             Email             68
             Facebook          61
             Google            58
             Referral          53
Not Applied  Facebook          67
             Google            66
             Instagram         61
             Referral          60
             Email             55
SAVE10       Google            66
             Email             61
             Instagram         57
             Referral          56
             Facebook          46
WINTER15     Instagram         68
             Email             66
             Facebook          54
             Referral          53
             Google            51
Name: count, dtype: int64

In [44]:
# exporting refined excel
df.to_excel('Dataset_refined.xlsx', sheet_name='Sales', index=False)